# Generated by Django 4.2.5 on 2023-09-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentstable',
            old_name='votes',
            new_name='likes',
        ),
    ]
